version: "3.4"
services:
       backend-app:
           container_name: test-backend
           image: test-backend
           env: 
           - MONGO_ENV: mongo
           - FIREBASE_CREDS: test
           restart: always
           build: .
           ports:
             - "2001:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'
