version: "2.2"
services:
       backend-app:
           container_name: test-backend
           image: test-backend
           environment: 
           - MONGO_ENV=mongo
           restart: always
           build: .
           ports:
             - "2001:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'