name: Build Backend

on:
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
     - name: Checkout repository
       uses: actions/checkout@v2
       
     - name: Create env file
       run: |
          ls
          touch .env
          echo MONGO_ENV=mongo >> .env
          echo FIREBASE_CREDS=${{ secrets.FIREBASE_CREDS }} >> .env       
        
     - name: Build Image   
       run: docker build -t ghcr.io/deanparrish/portfoliositebackend .   
       
     - name: Compose Image   
       run: docker compose up --no-start  
       
     - name: Push to Github Packages
       run: docker push ghcr.io/deanparrish/portfoliositebackend:latest
